<?php

use Illuminate\Database\Seeder;

class FoodsTableSeeder extends Seeder {

  public function run()
  {
    // Uncomment the below to wipe the table clean before populating
    DB::table('foods')->delete();
    $foods = array(
      ['id' => 1,
        'dessert' => 'ฮันนี่โทสต์ Honey Toast',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 2,
        'dessert' => 'เครปเค้กช็อกโกแลต',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 3,
        'dessert' => 'ช็อกโกแลตสดรสนม',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 4,
        'dessert' => 'คาราเมลคัสตาร์ด',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 5,
        'dessert' => 'บานอฟฟี่พาย',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 6,
        'dessert' => 'ขนมปังกรอบเนยน้ำตาล',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 7,
        'dessert' => 'ช็อกโกแลตโอริโอ้ทาร์ตต',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 8,
        'dessert' => 'สตรอเบอร์รี่ครีมพาย',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 9,
        'dessert' => 'เค้กครีมชีส',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 10,
        'dessert' => 'เค้กกล้วยหอม',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 11,
        'dessert' => 'ขนมปังชินนาม่อนโรล',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 12,
        'dessert' => 'เบลเยี่ยมวาฟเฟิล',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 13,
        'dessert' => 'กาแฟเวียนนา / VIENESE COFFEE',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 14,
        'dessert' => 'คาปูชิโน่ / CAPPUCCINO',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 15,
        'dessert' => 'คาราเมล คาปูชิโน่ / CARAMEL CAPPUCCINO',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 16,
        'dessert' => 'กาแฟมอคค่า / CAFFEE MOCHA',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 17,
        'dessert' => 'ช็อกโกแลตร้อน / HOT CHOCOLATE',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 18,
        'dessert' => 'เฮเซลนัทไอซ์ ลาตเต้ / HAZELNUT ICED LATTE',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 19,
        'dessert' => 'มิลค์กี่เวย์มอคค่า / MILKY WAY MOCHA',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 20,
        'dessert' => 'ชานมเย็น / ICED MILK TEA',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 21,
        'dessert' => 'อิตาเลี่ยนโซดา / ITALIAN SODA',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 22,
        'dessert' => 'ชาแอปเปิ้ล / ICED APPLE TEA',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
    );

    // Uncomment the below to run the seeder
    DB::table('foods')->insert($foods);
  }

}