<?php

use Illuminate\Database\Seeder;

class LocationsTableSeeder extends Seeder {

  public function run()
  {
    // Uncomment the below to wipe the table clean before populating
    DB::table('locations')->delete();

    $locations = array(
      ['id' => 1,
        'area' => 'คลองสาน',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 2,
        'area' => 'คลองเตย',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 3,
        'area' => 'ดินแดง',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 4,
        'area' => 'ดุสิต',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 5,
        'area' => 'ธนบุรี',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 6,
        'area' => 'บางกอกน้อย',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 7,
        'area' => 'บางกอกใหญ่',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 8,
        'area' => 'บางซื่อ',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 9,
        'area' => 'บางนา',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 10,
        'area' => 'บางบอน',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 11,
        'area' => 'บางเขน',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 12,
        'area' => 'บางแค',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 13,
        'area' => 'บึงกุ่ม',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 14,
        'area' => 'พญาไท',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 15,
        'area' => 'พระนคร',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 16,
        'area' => 'พระโขนง',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 17,
        'area' => 'ราชเทวี',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 18,
        'area' => 'จอมทอง',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 19,
        'area' => 'ทุ่งครุ',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 20,
        'area' => 'บางคอแหลม',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 21,
        'area' => 'ป้อมปราบศัตรูพ่าย',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 22,
        'area' => 'ยานนาวา',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 23,
        'area' => 'วัฒนา',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 24,
        'area' => 'หนองจอก',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 25,
        'area' => 'จตุจักร',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
        ['id' => 26,
        'area' => 'สาธร',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 27,
        'area' => 'ปทุมวัน',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 28,
        'area' => 'ภาษีเจริญ',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 29,
        'area' => 'ลาดพร้าว',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 30,
        'area' => 'บางพลัด',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 31,
        'area' => 'บางกะปิ',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 32,
        'area' => 'คันนายาว',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 33,
        'area' => 'ตลิ่งชัน',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 34,
        'area' => 'วังทองหลาง',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 35,
        'area' => 'มีนบุรี',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 36,
        'area' => 'สายไหม',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 37,
        'area' => 'ประเวศ',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 38,
        'area' => 'บางรัก',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 39,
        'area' => 'บางขุนเทียน',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 40,
        'area' => 'ทวีวัฒนา',
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
    );

    // Uncomment the below to run the seeder
    DB::table('locations')->insert($locations);
  }

}