<?php

use Illuminate\Database\Seeder;

class NearbiesTableSeeder extends Seeder {

  public function run()
  {
    // Uncomment the below to wipe the table clean before populating
    DB::table('nearbies')->delete();

    $nearbies = array(
      ['id' => 1,
        'shop_id' => 2,
        'location_id' => 19,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 2,
        'shop_id' => 3,
        'location_id' => 5,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 3,
        'shop_id' => 9,
        'location_id' => 16,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 4,
        'shop_id' => 11,
        'location_id' => 16,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 5,
        'shop_id' => 15,
        'location_id' => 25,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 6,
        'shop_id' => 18,
        'location_id' => 25,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 7,
        'shop_id' => 20,
        'location_id' => 3,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 8,
        'shop_id' => 28,
        'location_id' => 4,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 9,
        'shop_id' => 23,
        'location_id' => 1,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 10,
        'shop_id' => 31,
        'location_id' => 37,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 11,
        'shop_id' => 34,
        'location_id' => 18,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 12,
        'shop_id' => 35,
        'location_id' => 36,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 13,
        'shop_id' => 37,
        'location_id' => 36,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 14,
        'shop_id' => 42,
        'location_id' => 29,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 15,
        'shop_id' => 46,
        'location_id' => 27,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 16,
        'shop_id' => 50,
        'location_id' => 2,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 17,
        'shop_id' => 52,
        'location_id' => 14,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 18,
        'shop_id' => 58,
        'location_id' => 18,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 19,
        'shop_id' => 64,
        'location_id' => 38,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 20,
        'shop_id' => 67,
        'location_id' => 15,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 21,
        'shop_id' => 92,
        'location_id' => 13,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 22,
        'shop_id' => 98,
        'location_id' => 13,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],
      ['id' => 23,
        'shop_id' => 106,
        'location_id' => 20,
        'created_at' => new DateTime,
        'updated_at' => new DateTime],

    );

    // Uncomment the below to run the seeder
    DB::table('nearbies')->insert($nearbies);
  }

}